function(monky_download_verified url destination expected_hash)
  if(EXISTS "${destination}")
    file(SHA256 "${destination}" actual_hash)
    if(actual_hash STREQUAL expected_hash)
      return()
    endif()
  endif()
  get_filename_component(directory "${destination}" DIRECTORY)
  file(MAKE_DIRECTORY "${directory}")
  set(partial "${destination}.partial")
  foreach(attempt RANGE 1 3)
    # EXPECTED_HASH makes transport failures fatal before a retry is possible.
    file(DOWNLOAD "${url}" "${partial}"
      TLS_VERIFY TRUE TIMEOUT 120 INACTIVITY_TIMEOUT 30 STATUS download_status)
    list(GET download_status 0 download_code)
    if(download_code EQUAL 0)
      file(SHA256 "${partial}" actual_hash)
      if(NOT actual_hash STREQUAL expected_hash)
        file(REMOVE "${partial}")
        message(FATAL_ERROR "Pinned download hash mismatch for ${url}: ${actual_hash}")
      endif()
      file(RENAME "${partial}" "${destination}")
      return()
    endif()
    file(REMOVE "${partial}")
    if(attempt LESS 3)
      message(WARNING "Pinned download attempt ${attempt}/3 failed: ${download_status}. Retrying ${url}")
      execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1 COMMAND_ERROR_IS_FATAL ANY)
    endif()
  endforeach()
  message(FATAL_ERROR "Pinned download failed after 3 attempts: ${url}: ${download_status}")
endfunction()
