<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { withBase } from 'vitepress';
import {
  createServerInviteAppLink, createServerInviteLink, decodeServerInviteToken,
  type ServerInvite,
} from '../../../../packages/shared/src/serverInvites';

const props = defineProps<{ lang?: string }>();
const invite = ref<ServerInvite | null>(null);
const ready = ref(false);
const copyState = ref<'idle' | 'copied' | 'failed'>('idle');
const english = computed(() => props.lang === 'en');
const labels = computed(() => english.value ? {
  loading: 'Reading invitation…',
  invalid: 'This invitation is invalid or incomplete. Ask for a new link generated by Monky.',
  server: 'Server',
  address: 'Address',
  port: 'Port',
  open: 'Open in Monky',
  copy: 'Copy invitation',
  copied: 'Invitation copied!',
  copyFailed: 'Could not copy. Copy the full address from your browser instead.',
  download: 'Download or update Monky',
  fallback: 'If Monky did not open, use the button above. Your browser may ask for permission to open the installed app. You can also paste the link under Join with an invitation in Monky.',
  review: 'The app asks for confirmation before connecting. Review the server address; an invitation is not a verified server identity.',
  password: 'This invitation includes a password. Anyone with the link can use it. Only share it with people you trust.',
  noPassword: 'This invitation does not include a password. Enter one in Monky if the server requires it.',
  privacy: 'The invitation is decoded locally from the part after #, which is not sent to this website. Encoding is not encryption. HTTPS protects this page; it does not configure TLS or open ports on the Monky server.',
} : {
  loading: 'Lendo convite…',
  invalid: 'Este convite é inválido ou está incompleto. Peça um novo link gerado pelo Monky.',
  server: 'Servidor',
  address: 'Endereço',
  port: 'Porta',
  open: 'Abrir no Monky',
  copy: 'Copiar convite',
  copied: 'Convite copiado!',
  copyFailed: 'Não foi possível copiar. Copie o endereço completo pela barra do navegador.',
  download: 'Baixar ou atualizar o Monky',
  fallback: 'Se o Monky não abriu, use o botão acima. O navegador pode pedir permissão para abrir o aplicativo instalado. Você também pode colar o link em Entrar por convite no Monky.',
  review: 'O aplicativo pede confirmação antes de conectar. Confira o endereço; um convite não é uma identidade verificada do servidor.',
  password: 'Este convite inclui uma senha. Qualquer pessoa com o link poderá usá-la. Compartilhe apenas com quem você confia.',
  noPassword: 'Este convite não inclui senha. Informe-a no Monky se o servidor exigir.',
  privacy: 'O convite é decodificado localmente a partir do trecho após #, que não é enviado a este site. Codificação não é criptografia. O HTTPS protege esta página; não configura TLS nem abre portas no servidor Monky.',
});
const appLink = computed(() => invite.value ? createServerInviteAppLink(invite.value) : '');
const downloadLink = computed(() => withBase(english.value ? '/en/download.html' : '/download.html'));
let generation = 0;

function readInvite(): void {
  generation++;
  copyState.value = 'idle';
  const parsed = decodeServerInviteToken(window.location.hash.slice(1));
  invite.value = parsed.ok ? parsed.invite : null;
  ready.value = true;
  if (parsed.ok) {
    try {
      window.location.assign(createServerInviteAppLink(parsed.invite));
    } catch {
      console.warn('[Invites] The browser did not launch Monky; manual opening remains available.');
    }
  }
}

async function copyInvite(): Promise<void> {
  if (!invite.value) return;
  const current = generation;
  try {
    await navigator.clipboard.writeText(createServerInviteLink(invite.value));
    if (current === generation) copyState.value = 'copied';
  } catch {
    if (current === generation) copyState.value = 'failed';
  }
}

onMounted(() => {
  readInvite();
  window.addEventListener('hashchange', readInvite);
});
onBeforeUnmount(() => {
  generation++;
  window.removeEventListener('hashchange', readInvite);
});
</script>

<template>
  <section class="server-invite" aria-live="polite">
    <p v-if="!ready">{{ labels.loading }}</p>
    <template v-else-if="invite">
      <dl>
        <dt>{{ labels.server }}</dt><dd>{{ invite.name || 'Monky' }}</dd>
        <dt>{{ labels.address }}</dt><dd data-invite-host>{{ invite.host }}</dd>
        <dt>{{ labels.port }}</dt><dd data-invite-port>{{ invite.port }}</dd>
      </dl>
      <p>{{ labels.review }}</p>
      <p :class="{ 'invite-password-warning': invite.password }">{{ invite.password ? labels.password : labels.noPassword }}</p>
      <div class="invite-actions">
        <a :href="appLink" class="invite-primary">{{ labels.open }}</a>
        <button type="button" @click="copyInvite">{{ labels.copy }}</button>
        <a :href="downloadLink">{{ labels.download }}</a>
      </div>
      <p v-if="copyState !== 'idle'" role="status">{{ copyState === 'copied' ? labels.copied : labels.copyFailed }}</p>
      <p>{{ labels.fallback }}</p>
    </template>
    <template v-else>
      <p role="alert">{{ labels.invalid }}</p>
      <a :href="downloadLink">{{ labels.download }}</a>
    </template>
    <p class="invite-privacy">{{ labels.privacy }}</p>
  </section>
</template>

<style scoped>
.server-invite {
  padding: 24px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 12px;
  background: var(--vp-c-bg-soft);
}
.server-invite dl {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 8px 20px;
}
.server-invite dt { font-weight: 600; }
.server-invite dd { margin: 0; overflow-wrap: anywhere; }
.invite-actions { display: flex; flex-wrap: wrap; gap: 12px; margin: 24px 0; }
.invite-actions a, .invite-actions button {
  padding: 10px 16px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  font-weight: 600;
  text-decoration: none;
  cursor: pointer;
}
.invite-actions .invite-primary {
  background: var(--vp-c-brand-1);
  color: var(--vp-c-white);
  border-color: transparent;
}
.invite-actions a:focus-visible, .invite-actions button:focus-visible {
  outline: 2px solid var(--vp-c-brand-1);
  outline-offset: 3px;
}
.invite-password-warning { font-weight: 600; }
.invite-privacy { font-size: 13px; color: var(--vp-c-text-2); }
</style>
